spring.application.name=Ejercicio10

# Conexión principal (usando variables de entorno)
spring.datasource.url=jdbc:postgresql://dpg-d7oa2vpj2pic739ntjh0-a.oregon-postgres.render.com:5432/ejercicio10
spring.datasource.username=ejercicio10_user
spring.datasource.password=dnZNZSTb5CcPcfirgvdQAuVliVB159b4
# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialecto para optimizar consultas a PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect